[phases.setup]
nixPkgs = ['python312', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python main.py'

[variables]
PYTHONUNBUFFERED = '1'
GOOGLE_CHROME_BIN = '/nix/store/*-chromium-*/bin/chromium'
CHROMEDRIVER_PATH = '/nix/store/*-chromedriver-*/bin/chromedriver'
